cd ~
if ~exist('datapath', 'var')
    datapath = 'Documents/master/datasets/Univariate_arff';
end

if ~exist('savepath', 'var')
    savepath = 'Documents/master/datasets/Univariate_arff';
end

if ~exist('n_features', 'var')
    n_features = 1000;
end

benchmark = [ "Adiac", "ArrowHead", "Beef", "BeetleFly", "BirdChicken", "Car", "CBF", "ChlorineConcentration",...
	    "CinCECGtorso", "Coffee", "Computers", "CricketX", "CricketY", "CricketZ", "DiatomSizeReduction",...
	    "DistalPhalanxOutlineAgeGroup", "DistalPhalanxOutlineCorrect", "DistalPhalanxTW", "Earthquakes",...
	    "ECG200", "ECG5000", "ECGFiveDays", "ElectricDevices", "FaceAll", "FaceFour", "FacesUCR",...
	    "FiftyWords", "Fish", "FordA", "FordB", "GunPoint", "Ham", "HandOutlines", "Haptics", "Herring",...
	    "InlineSkate", "InsectWingbeatSound", "ItalyPowerDemand", "LargeKitchenAppliances", "Lightning2",...
	    "Lightning7", "Mallat", "Meat", "MedicalImages", "MiddlePhalanxOutlineAgeGroup", "MiddlePhalanxOutlineCorrect",...
	    "MiddlePhalanxTW", "MoteStrain", "NonInvasiveFetalECGThorax1", "NonInvasiveFetalECGThorax2", "OliveOil",...
	    "OSULeaf", "PhalangesOutlinesCorrect", "Phoneme", "Plane", "ProximalPhalanxOutlineAgeGroup",...
	    "ProximalPhalanxOutlineCorrect", "ProximalPhalanxTW", "RefrigerationDevices", "ScreenType", "ShapeletSim",...
	    "ShapesAll", "SmallKitchenAppliances", "SonyAIBORobotSurface1", "SonyAIBORobotSurface2", "StarLightCurves",...
	    "Strawberry", "SwedishLeaf", "Symbols", "SyntheticControl", "ToeSegmentation1", "ToeSegmentation2",...
	    "Trace", "TwoLeadECG", "TwoPatterns", "UWaveGestureLibraryX", "UWaveGestureLibraryY", "UWaveGestureLibraryZ",...
	    "UWaveGestureLibraryAll", "Wafer", "Wine", "WordSynonyms", "Worms", "WormsTwoClass", "Yoga",...
        "ACSF1", "BME", "Chinatown", "Crop", "EOGHorizontalSignal", "EOGVerticalSignal", ...
        "EthanolLevel", "FreezerRegularTrain", "FreezerSmallTrain", "GunPointAgeSpan", ...
        "GunPointMaleVersusFemale", "GunPointOldVersusYoung", "HouseTwenty", "InsectEPGRegularTrain",...
        "InsectEPGSmallTrain", "MixedShapesRegularTrain", "MixedShapesSmallTrain", "PigAirwayPressure", ...
        "PigArtPressure", "PigCVP", "PowerCons", "Rock", "SemgHandGenderCh2", "SemgHandMovementCh2", ...
        "SemgHandSubjectCh2", "SmoothSubspace", "UMD"];

times_train = zeros(1,length(benchmark));
times_test = zeros(1,length(benchmark));

mkdir(fullfile(savepath, 'datasets_mat'))

for i=1:length(benchmark)

    t_train = extract_hctsa(datapath, savepath, convertStringsToChars(benchmark(i)), ...
        n_features, 'train');
    times_train(i) = t_train;

    t_test = extract_hctsa(datapath, savepath, convertStringsToChars(benchmark(i)), ...
        n_features, 'test');
    times_test(i) = t_test;

end